version: "3"

services:
  backend:
    build: ./app
    command: python manage.py runserver localhost:8000
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - .:/code
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: luxar
      POSTGRES_PASSWORD: sYst3m0ps
      POSTGRES_DB: django

volumes:
  service: