version: "3"

services:
  backend:
    build: ./app
    command: gunicorn settings.wsgi:application --bind 0.0.0.0:8000
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - db
    links:
      - db
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: luxar
      POSTGRES_PASSWORD: sYst3m0ps
      POSTGRES_DB: django

volumes:
  service: